package com.example.smokinglog

import kotlin.random.Random

enum class HumorTopic { TODAY, HISTORY, INSIGHTS, SETTINGS }

/** 360 original, standalone sentences: 60 per screen or action-feedback category. */
object Humor {
    private val messages = mapOf(
        HumorTopic.TODAY to listOf(
            "The universe has scheduled today without checking your availability.",
            "Your craving has mistaken its volume for a qualification.",
            "Free will remains available despite several strongly worded cravings.",
            "Today comes without instructions because the universe lost the stapler.",
            "An urge is a suggestion with a regrettable management style.",
            "Nicotine has called another meeting that could have been a thought.",
            "The next five minutes have declined to predict the rest.",
            "The galaxy can wait while you locate your other sock.",
            "Your habits are counting on you not reading the small print.",
            "A craving is terribly urgent about something it cannot explain.",
            "The present moment is small enough to manage without scaffolding.",
            "Today has arrived wearing yesterday's confidence and somebody else's trousers.",
            "The kettle offers fewer opinions than most forms of destiny.",
            "Your next decision requires considerably less than a five-year plan.",
            "Nicotine would like a word and has prepared seventeen thousand.",
            "The day is still under construction, so mind the assumptions.",
            "You can question an urge without forming a parliamentary committee.",
            "The craving's deadline was invented by the craving.",
            "A brief pause could ruin nicotine's carefully prepared presentation.",
            "The universe has no position on your afternoon, which helps.",
            "Your attention is not obliged to answer every doorbell.",
            "Today needs a participant, not a flawlessly calibrated astronaut.",
            "An impulse has arrived without references and expects a corner office.",
            "The impulse has arrived first and mistaken this for being elected.",
            "The future keeps demanding answers before supplying the questions.",
            "A small decision can be made without consulting the constellations.",
            "Your craving's business card is doing most of the work.",
            "Today's control room is being run by a mammal with errands.",
            "Nicotine's argument relies heavily on nicotine agreeing with nicotine.",
            "You may postpone an impulse without rescheduling the solar system.",
            "Reality has accepted your arrival despite the missing paperwork.",
            "The morning's prophecies are mostly caffeine in an impressive hat.",
            "Your habits have grown suspicious of this new observation programme.",
            "A cup of tea rarely insists it is your destiny.",
            "The urge has marked itself important in its own filing system.",
            "The next minute is refreshingly unqualified to judge the previous one.",
            "Today is a first draft with unusually convincing weather.",
            "You are allowed to change direction without indicating to Jupiter.",
            "An automatic habit dislikes discovering that you have found the manual.",
            "The universe's grand plan appears to involve finding its glasses.",
            "One manageable moment beats a heroic promise with structural problems.",
            "Your craving has confused a recurring role with ownership of the programme.",
            "The afternoon is mostly time wearing unnecessarily dramatic lighting.",
            "Even the galaxy gets through things one inconvenient second at a time.",
            "Your plans may be revised without convening the moon.",
            "The urgent department has been caught labelling everything urgent.",
            "You can notice a thought without offering it accommodation.",
            "A pause is a perfectly respectable use of spacetime.",
            "Today has outsourced perfection to an unreachable telephone number.",
            "The craving's spokesperson has declined to provide independent evidence.",
            "Your previous decision has no legal custody of the next one.",
            "The day has enough gravity without your supplying extra seriousness.",
            "Nicotine is making a proposal with suspiciously rehearsed enthusiasm.",
            "The universe tolerates small steps despite measuring everything in ridiculous units.",
            "Your thoughts are visiting, not buying the property.",
            "The present is the only bit of time accepting walk-ins.",
            "The next moment has arrived in plain clothes to avoid expectations.",
            "The craving has a megaphone but no planning permission.",
            "Today's chaos is accepting visitors one mildly improbable moment at a time.",
            "Destiny can leave a message while you decide what happens next.",
        ),
        HumorTopic.HISTORY to listOf(
            "Yesterday has been filed where it can do less improvising.",
            "Your past has reluctantly agreed to appear in chronological order.",
            "Hindsight is memory wearing spectacles it bought afterwards.",
            "The archive contains facts rather than a prosecution team.",
            "Your previous decisions have arrived for inspection without their excuses.",
            "History looks tidier once it stops happening to you.",
            "The log remembers details your memory has promoted to folklore.",
            "Yesterday's chaos has been persuaded to sit in rows.",
            "These timestamps are remarkably precise for witnesses without watches.",
            "The past is now available without its original background noise.",
            "Your memory has requested several flattering revisions to the evidence.",
            "Chronology is what happens when events finally respect a queue.",
            "The archive has no eyebrow to raise at you.",
            "Your earlier self was operating with considerably less hindsight.",
            "An honest record is a surprisingly effective antidote to vague recollection.",
            "Yesterday remains unchanged by today's superior access to yesterday.",
            "The log has declined to turn Tuesday into a personality assessment.",
            "Time travel remains unavailable, but the edit button has references.",
            "Your entries are allowed to be accurate without being inspirational.",
            "The past has stopped moving long enough to count it.",
            "Memory prefers highlights, whereas the log also keeps the plumbing.",
            "These events have retired from reality and taken up documentation.",
            "The archive is not disappointed because it lacks the necessary glands.",
            "Yesterday has submitted its paperwork with the confidence of yesterday.",
            "Your habits left footprints despite having made no travel arrangements.",
            "The log offers perspective without claiming to have been there emotionally.",
            "Even untidy days become presentable when given their own timestamp.",
            "The record is keeping your place while memory wanders off.",
            "Your past can be examined without being appointed your future.",
            "Hindsight never mentions how late it arrived.",
            "The archive has rejected next Thursday's report as suspiciously premature.",
            "Every entry is a witness with unusually good handwriting.",
            "Yesterday's urgent business is today's scrollable material.",
            "The log has preserved the facts without preserving the panic.",
            "Your memory and the timestamps have agreed to disagree politely.",
            "The past has been organised against its deeply held principles.",
            "These entries have escaped oblivion and landed somewhere with worse wallpaper.",
            "The archive is a library with very little interest in shushing you.",
            "Your history has more nuance than its numerical summary can carry.",
            "The calendar has turned several complicated experiences into little squares.",
            "A timestamp is an event's attempt at a forwarding address.",
            "These records are here for context rather than character references.",
            "The past has acquired a scrollbar and lost some authority.",
            "Memory is a brilliant novelist with unreliable bookkeeping.",
            "Yesterday is easier to inspect now that it has stopped shouting.",
            "Your log can accommodate a difficult day without becoming one.",
            "The chronology has been checked by time's least imaginative employee.",
            "The archive accepts corrections without a lengthy redemption ceremony.",
            "Recorded facts remain useful even when they decline to be flattering.",
            "The archive has saved the story without demanding film rights.",
            "Your previous self has left notes rather than binding instructions.",
            "History is much easier to navigate without the original weather.",
            "The log has converted a blur into individually addressable blurs.",
            "The museum of your week has mercifully omitted the gift shop.",
            "The archive keeps receipts for moments that expected to remain anonymous.",
            "History settled for timestamps after the cave paintings exceeded the budget.",
            "These entries survived the day and deserve a comfortable shelf.",
            "Your past is being displayed without its director's commentary.",
            "Yesterday's plot holes are easier to spot without Tuesday standing in them.",
            "Yesterday may be consulted without being put back in charge.",
        ),
        HumorTopic.INSIGHTS to listOf(
            "The average has flattened your week and called it helpful.",
            "Your habits have discovered that graphs can remember their names.",
            "Statistics is what happens when counting develops a superiority complex.",
            "The chart has axes because even data needs boundaries.",
            "A trend is a direction rather than a signed confession.",
            "The numbers have formed a queue and become a dashboard.",
            "Your week now has a shape, which is more than Monday managed.",
            "The graph cannot predict tomorrow because tomorrow refuses to send samples.",
            "Arithmetic has processed the drama and returned a modest decimal.",
            "Averages exist because experiencing an entire week simultaneously would be exhausting.",
            "Two halves share an equivalent but insist on separate event badges.",
            "Correlation keeps applying for causation's job without the qualifications.",
            "The chart's confidence comes largely from standing on a grid.",
            "Your totals have declined to write a speech about your character.",
            "The decimal point is doing an unreasonable amount of organisational work.",
            "Seven days is a week with most of the anecdotes removed.",
            "Thirty days gives coincidence more opportunities to look employed.",
            "Even zero deserves its own rather circular place in the report.",
            "The calculator has considered your circumstances and requested a number.",
            "A bar chart is a fence built from things that happened.",
            "Your data has changed clothes and become a visualisation.",
            "The graph offers perspective without requiring a more expensive telescope.",
            "Patterns are easier to spot once the individual days stop interrupting.",
            "The chart has mistaken a difficult Tuesday for a perfectly ordinary rectangle.",
            "The labels prevent your habits from impersonating abstract art.",
            "Your longest interval has finally found a legitimate reason to boast.",
            "The chart is informative despite having no idea what lunch was like.",
            "Progress has never been particularly interested in straight lines.",
            "The numbers are precise about quantities and hopeless about being you.",
            "A single day is an unreliable spokesperson for the entire month.",
            "The graph has no agenda beyond standing upright and being legible.",
            "Your statistics are less mysterious now that they have names.",
            "The y-axis has risen above office politics by remaining vertical.",
            "Tomorrow's results are unavailable due to tomorrow's persistent lateness.",
            "The graph has booked a tiny orchestra for the smaller developments.",
            "The total has gathered everyone together and forgotten their individual stories.",
            "These bars contain information rather than refreshments, which disappoints some visitors.",
            "Your week has been translated into a language calculators find moving.",
            "A flat line is a shape rather than a personal remark.",
            "The data is here to inform you, despite its managerial appearance.",
            "Your highest day has not been appointed ambassador for all days.",
            "The scale measures quantities because measuring intentions broke the prototype.",
            "A useful pattern does not require a dramatic soundtrack.",
            "The calculator refuses to discuss its feelings about fractions.",
            "Your daily average has met no actual day quite like itself.",
            "The graph makes no promises because its lawyer is a ruler.",
            "A longer interval gives the timeline more room to put its feet up.",
            "Resisted urges have joined the statistics without bringing any smoke.",
            "Your totals have been calculated without consulting a single horoscope.",
            "The chart cannot raise an eyebrow without invalidating both axes.",
            "Each bar is a day wearing a more manageable silhouette.",
            "The graph has arranged your week without once asking about parking.",
            "The numbers remain available for consultation rather than worship.",
            "Patterns are clues with better posture than guesses.",
            "Your statistics remain stubbornly unimpressed by the dramatic lighting.",
            "Your chart is a map whose mountains are made of arithmetic.",
            "One data point is a very small committee.",
            "Statistics has removed the plot and retained the useful bits.",
            "The graph's crystal ball has been reassigned as a paperweight.",
            "Your next decision is not awaiting approval from the previous thirty days.",
        ),
        HumorTopic.SETTINGS to listOf(
            "Free will has been given a settings page and minimal supervision.",
            "Your preferences may be changed without a constitutional crisis.",
            "A daily target is a compass with no disciplinary powers.",
            "The universe has defaults, but nobody remembers selecting them.",
            "Your data has declined an exciting career in targeted advertising.",
            "The export button gives your facts a small suitcase.",
            "Settings is where vague intentions acquire a text field.",
            "A target should assist you rather than develop a throne.",
            "Your chosen number is not engraved on anything expensive.",
            "The configuration department has misplaced its license to overrule you.",
            "CSV is what happens when facts agree to travel single file.",
            "Your preferences do not require a supporting letter from Saturn.",
            "This app has fewer opinions once you tell it yours.",
            "A saved setting is a decision spared another meeting.",
            "Your data belongs to you despite its growing collection of commas.",
            "The daily target is adjustable because humans inconveniently have days.",
            "Importing introduces yesterday's facts to a different set of furniture.",
            "The export format is plain because the numbers refused evening wear.",
            "Your settings have no diplomatic obligations to anybody else's settings.",
            "A useful target fits your life without requiring major demolition.",
            "Configuration is the art of making software stop guessing so confidently.",
            "Your preferences are allowed to evolve without shedding an exoskeleton.",
            "The app's networking department never recovered from not being hired.",
            "Changing your target does not require changing your identity documents.",
            "A CSV file is a spreadsheet before it develops expensive tastes.",
            "Your exported facts will travel without an accompanying motivational speaker.",
            "The universe may be fixed, but your daily target isn't.",
            "Your settings are personal without needing a personality test.",
            "Even the default configuration was once somebody's guess.",
            "A target can be ambitious without buying a ceremonial sword.",
            "Your records have not consented to becoming a marketing demographic.",
            "The preferences department has finally accepted that you have preferences.",
            "An exported log is your memory with better luggage discipline.",
            "The configuration has room for decisions made after breakfast.",
            "Your target is permitted to use decimals without becoming pretentious.",
            "The app's advertising division consists of an empty chair.",
            "The export button is a departure lounge with excellent punctuation.",
            "Your settings can change without disturbing the migration patterns of planets.",
            "A practical target beats an impressive number nobody wants to meet.",
            "The app awaits your instructions with suspiciously uncharacteristic patience.",
            "Your data can be portable without developing a nomadic philosophy.",
            "A backup is a spare past kept somewhere sensible.",
            "The import button appreciates knowing which past you intend to bring.",
            "Your preferences have been granted sovereignty over this modest rectangle.",
            "The daily target has no authority to confiscate your afternoon.",
            "CSV files separate facts with commas because tiny fences cost extra.",
            "Humanity's access to settings remains an intriguing experiment.",
            "Software becomes more manageable once its suggestions acquire an off switch.",
            "Your exported history will contain rows rather than a dramatic reenactment.",
            "A considerate target leaves room for being a mammal.",
            "The settings page is the cockpit without the terrifying number of levers.",
            "Your records are local residents with optional travel arrangements.",
            "The right configuration is usually less impressive than the wrong manifesto.",
            "A CSV file has no dress code beyond correctly placed commas.",
            "The save button is unusually literal about its ambitions.",
            "Preferences are opinions the software has agreed to remember.",
            "The app can remember your choice without forming an attachment to it.",
            "A backup gives a misplaced phone one fewer opportunity for drama.",
            "Your data's exit interview consists entirely of choosing a filename.",
            "The universe remains unconfigurable, but this is a respectable start.",
        ),
    )

    private val smokedMessages = listOf(
        "The evidence has stopped being a rumour.",
        "Your memory's creative department has one less assignment.",
        "Your tap has supplied the plot with an actual date.",
        "Reality now has a written account to argue with.",
        "That entry has secured its place in the queue for arithmetic.",
        "The log has accepted reality without demanding a nicer version.",
        "Your honesty has spared a future graph some imaginative archaeology.",
        "Another fact has arrived wearing all the appropriate coordinates.",
        "The event has been filed under things that actually happened.",
        "Your phone has nodded in the limited manner available to phones.",
        "The spreadsheet's future biographer will appreciate this level of detail.",
        "The event's autobiography now consists of a date and some arithmetic.",
        "The event has surrendered its right to a mysterious backstory.",
        "No cosmic verdict accompanies this receipt.",
        "Your honesty is doing useful work without wearing a lanyard.",
        "One tap has saved tomorrow from a surprisingly boring detective story.",
        "The log has caught reality before it could change its account.",
        "Your entry has joined a database with no interest in gossip.",
        "The universe ignored the tap, but the log has better manners.",
        "Your future self has received a memo from a reliable source.",
        "The truth has arrived without an interpretive dance.",
        "The calculator has put on its serious little face.",
        "The paperwork has finally caught up with the plot.",
        "A modest fact has been rescued from a dramatic retelling.",
        "The calculator thanks you for submitting actual events rather than vibes.",
        "Your entry has found a seat in tomorrow's arithmetic.",
        "The count has advanced without making a speech.",
        "The log welcomes your contribution to the science of what happened.",
        "Your recollection has been spared the indignity of cross-examination.",
        "Your tap has prevented a detail from becoming a local legend.",
        "One fewer fact is entrusted to the committee inside your head.",
        "The evidence has taken a seat where tomorrow can find it.",
        "Your log has received the news without dropping its monocle.",
        "The incident has been numbered despite requesting a more theatrical title.",
        "An honest entry has quietly improved the quality of the sequel.",
        "Your phone has performed a small and unusually useful act of bureaucracy.",
        "The event is no longer relying on eyewitness accounts from caffeine.",
        "Another fact has been domesticated by the simple application of a timestamp.",
        "The archive's tiny doorman has waved another fact inside.",
        "Your accuracy has made an accountant somewhere inexplicably less tense.",
        "The record has gained detail without demanding a bigger dressing room.",
        "A little more reality has been squeezed into this modest rectangle.",
        "The log remains admirably calm for something that knows the numbers.",
        "Your tap has put a nametag on an otherwise anonymous moment.",
        "The event can now be found without consulting the village oracle.",
        "The database has accepted your entry with the warmth of organised shelving.",
        "Honesty has completed its work and gone looking for a biscuit.",
        "The count is now less dependent on optimistic storytelling.",
        "Your future chart has received another tiny piece of furniture.",
        "The facts have been recorded without a ceremonial unveiling.",
        "Your log has acquired evidence rather than a strongly held suspicion.",
        "Your entry has bypassed mythology and gone straight to bookkeeping.",
        "The timestamp has attached itself with the persistence of a luggage label.",
        "Reality has been admitted to the spreadsheet through the proper entrance.",
        "The incident has failed to secure diplomatic immunity from arithmetic.",
        "A future calculation has been given something solid to stand on.",
        "Your honesty has shortened an imaginary investigation considerably.",
        "The entry is official despite the complete absence of a ribbon.",
        "Another moment has been prevented from escaping through a loophole in memory.",
        "The log remains a notebook rather than a disappointed Victorian relative.",
    )

    private val resistedMessages = listOf(
        "You declined an impulse that had already booked a meeting room.",
        "An urge has discovered that wanting something is not planning permission.",
        "Your craving's sales pitch has been returned unopened.",
        "Nicotine requested a manager and was introduced to you.",
        "Your pause has caused a small scheduling disaster for the habit.",
        "You declined the starring role in a very repetitive advert.",
        "Your craving has discovered that enthusiasm is not legal authority.",
        "You have successfully inconvenienced a remarkably pushy molecule.",
        "The habit's automatic doors have encountered a manual decision.",
        "Your lungs would applaud if the engineering were less complicated.",
        "One urge has been demoted from instruction to unsolicited advice.",
        "Your habit's prediction department is facing an awkward review.",
        "That was an excellent refusal for someone without a ceremonial sceptre.",
        "Your free will has remembered its password.",
        "You have declined an invitation from a spectacularly persistent organiser.",
        "The craving's five-star emergency has been reviewed as ordinary wanting.",
        "An impulse came for obedience and received customer feedback.",
        "The habit has discovered an unexpected human in its machinery.",
        "You earned a quiet victory with remarkably low catering costs.",
        "Your choice has made the imaginary applause briefly less imaginary.",
        "Somewhere, a tiny trumpeter has been given meaningful work.",
        "Your craving is now negotiating with a closed reception desk.",
        "You have politely declined to be managed by a sensation.",
        "The urge has lost its self-appointed position as chief executive.",
        "Your pause was louder than the craving's entire advertising budget.",
        "You confused a habit by consulting the person involved.",
        "Your refusal has forced the craving to revise its confident brochure.",
        "One tiny rebellion has passed without destabilising the tea.",
        "Your habit is checking whether this counts as an unauthorised update.",
        "That choice deserves a medal too sensible to require polishing.",
        "The impulse's business model has encountered an inconvenient customer decision.",
        "Your refusal worked perfectly despite being delivered without a laser sword.",
        "You resisted an urge without needing a prophecy about it.",
        "Your habit has encountered a plot twist with excellent boundaries.",
        "You have given an automatic response some unexpected leave.",
        "You handled that urge with fewer explosions than the films recommend.",
        "Your craving has been reminded that it is not the landlord.",
        "An urgent feeling has failed its application to become compulsory.",
        "You let the urge speak without offering it your signature.",
        "Your habit's script has acquired a beautifully inconvenient blank line.",
        "You have created a small victory with no assembly required.",
        "The craving's shortcut has unexpectedly led to a firm decision.",
        "Your patience has inconvenienced an entire microscopic marketing department.",
        "That urge brought demands to a situation where you brought choices.",
        "You defeated a small insistence with an even smaller word.",
        "Your refusal is valid even without a witness from the moon.",
        "One pushy impulse has failed to secure a controlling interest.",
        "You have changed the next scene without consulting the screenwriter.",
        "The habit has been caught assuming it already had your consent.",
        "Your decision has cancelled a rerun without cancelling the entire day.",
        "Your independence made a brief and beautifully inconvenient house call.",
        "You interrupted a familiar routine without breaking spacetime.",
        "The craving's dramatic entrance has not guaranteed it a performance.",
        "Your pause has denied an impulse its preferred special effects.",
        "You left nicotine holding a clipboard and several unanswered questions.",
        "The habit has received a refusal with unusually clear punctuation.",
        "Your choice has made the autopilot look briefly unnecessary.",
        "An urge requested the wheel and received directions to the passenger seat.",
        "You stayed in charge while the impulse practised sounding official.",
        "Your victory fits in a moment and requires no storage permit.",
    )
    fun next(topic: HumorTopic, previous: String? = null, random: Random = Random.Default): String {
        val choices = messages.getValue(topic)
        val eligible = choices.filterNot { it == previous }.ifEmpty { choices }
        return eligible[random.nextInt(eligible.size)]
    }

    fun smoked(amount: Double, random: Random = Random.Default): String =
        "${if (amount == 1.0) "Whole cigarette" else "Half cigarette"} logged. ${smokedMessages.random(random)}"

    fun resisted(random: Random = Random.Default): String = resistedMessages.random(random)

    fun allFor(topic: HumorTopic): List<String> = messages.getValue(topic)

    fun allSmokedFollowUps(): List<String> = smokedMessages

    fun allResistedCompliments(): List<String> = resistedMessages
}
