package com.example.smokinglog

import kotlin.random.Random

enum class HumorTopic { TODAY, HISTORY, INSIGHTS, SETTINGS }

/** Complete cosmic absurdities, kept outside the UI so every screen can share the joke. */
object Humor {
    private val todayMessages = listOf(
        "Today's craving has arrived without an appointment or trousers.",
        "Your lungs have requested a less exciting afternoon.",
        "Nicotine has submitted a proposal written entirely in crayon.",
        "The next cigarette is currently lost near Alpha Centauri.",
        "A smoke-free minute knows several influential minutes.",
        "The craving has misplaced both urgency and its personality.",
        "Your lighter has been demoted to decorative archaeology.",
        "Today has several exits, none requiring smoke.",
        "The tobacco lobby in your head forgot the biscuits.",
        "One quiet breath outperformed an entire marketing department.",
        "Your next urge is loud but has no jurisdiction.",
        "The universe recommends tea because it already made some.",
        "A cigarette break is a break in a poor disguise.",
        "Your lungs are plotting the introduction of oxygen.",
        "The craving has mistaken repetition for an argument.",
        "Today is mostly harmless and entirely unsupervised.",
        "Free will has appeared and wants the window seat.",
        "The ashtray remains available for early retirement.",
        "A five-minute delay has bewildered the nicotine authorities.",
        "Your habit called a meeting nobody needs to attend.",
        "The next healthy choice is hiding behind Tuesday.",
        "Nicotine is knocking on the wrong planet.",
        "Your breathing apparatus prefers air without plot twists.",
        "The urge is temporary despite its dramatic training.",
        "Today requires no heroics beyond doing something else.",
        "A glass of water has volunteered for crisis management.",
        "The cigarette can wait; it has nowhere interesting to be.",
        "Your lungs voted for fewer indoor weather systems.",
        "This craving will pass after remembering another engagement.",
        "The day merely requires better editing.",
        "A deep breath arrived without setting fire to anything.",
        "Your habit is confident because nobody showed it the minutes.",
        "The Guide lists smoking under avoidable administrative fog.",
        "Today's mission is improbable and wearing sensible shoes.",
        "The nicotine gremlin has been given a puzzle book.",
        "Your future self sent a hopeful postcard.",
        "A craving is chemistry making a long speech.",
        "The nearest cigarette has no useful career advice.",
        "Your lungs are not sentimental about combustion.",
        "The afternoon may proceed without special effects.",
        "Nicotine declared an emergency in a nonexistent department.",
        "A skipped cigarette leaves room for sandwiches.",
        "The craving brought thunder but forgot the weather.",
        "Your choices remain yours despite several pushy molecules.",
        "The smoke alarm in your mind is selling smoke.",
        "One less cigarette is an excellent oddity.",
        "The habit has momentum but dreadful steering.",
        "Your tea is prepared to negotiate.",
        "The universe is expanding, so there is room to wait.",
        "Today's count has no authority over tomorrow.",
        "A craving cannot read clocks or social cues.",
        "Your lungs filed a request marked reasonably urgent.",
        "The next ten minutes are hiring distractions.",
        "Nicotine promises relief from the problem it invented.",
        "The day remains salvageable and knows where its towel is.",
        "A short walk can confuse a craving completely.",
        "Your habit expected obedience and prepared no contingency.",
        "The current urge is all headline and no article.",
        "Breathing freely is suspiciously affordable.",
        "You need only outlast a molecule with no calendar.",
    )

    private val historyMessages = listOf(
        "The past has been timestamped and can deny nothing.",
        "Yesterday is available for inspection but refuses interviews.",
        "Every entry is a fact in rumpled clothes.",
        "The archive remembers what Tuesday hoped everyone forgot.",
        "History repeats itself because it lost the receipt.",
        "Old cravings look smaller in chronological order.",
        "The log contains no judgement, only accurate clocks.",
        "Past cigarettes now work for the Department of Numbers.",
        "Hindsight has arrived with binoculars and no tact.",
        "The timeline lacks enough imagination to lie.",
        "Yesterday filed its report under Somehow Happened.",
        "These entries are footprints from a habit with muddy shoes.",
        "The record annoys several vague memories.",
        "Your history is data, not a disappointed headmaster.",
        "The archive kept the facts and misplaced the guilt.",
        "Every half cigarette receives full administrative recognition.",
        "The past cannot change, but its spelling can.",
        "This timeline survived days assembled without instructions.",
        "Old urges seem less imperial when sorted by date.",
        "The log knows what happened and stops there.",
        "Yesterday was complicated and submitted no apology.",
        "The chronology proceeds from one tea to another.",
        "Your previous self left notes instead of navigation charts.",
        "The evidence is suspiciously well timestamped.",
        "Each entry survives in locally sourced electrons.",
        "The past is another country with dreadful smoking regulations.",
        "This archive accepts corrections without a time machine.",
        "Old cigarettes become rows and lose their mystery.",
        "The log owns no red pen or moral vocabulary.",
        "Yesterday's chaos has been alphabetized by time.",
        "These facts refuse to practise stern expressions.",
        "A deleted mistake returns to the administrative void.",
        "The timeline reveals patterns and badly behaved lunches.",
        "Past cravings have lost their present voting rights.",
        "The archive is patient, unlike interstellar historians.",
        "Your smoking history has acquired adequate shelving.",
        "Every honest entry makes memory less employable.",
        "The record contains events, not character references.",
        "Yesterday's cigarette is merely a database citizen.",
        "The timeline arranged the mess into tasteful cards.",
        "History looks tidier after the smoke leaves.",
        "Your old habit left numerical fingerprints.",
        "The archive permits reflection but forbids dramatic gavels.",
        "These timestamps know nothing of shame.",
        "A corrected entry causes no worthwhile paradox.",
        "The past can stop showing off now.",
        "Your log is a map drawn after visiting dragons.",
        "The chronology includes detours but charges no tolls.",
        "Old data waits patiently and never smokes indoors.",
        "The record put yesterday in a sensible container.",
        "Every entry says happened, never doomed.",
        "The archive is immune to blame and excuses.",
        "Your past self did fieldwork under questionable management.",
        "The timeline has excellent recall and dreadful gossip skills.",
        "These numbers survived reality and deserve a shelf.",
        "Previous cigarettes now serve as cautionary decimals.",
        "The log observes everything and lectures nothing.",
        "Yesterday remains available in dark mode.",
        "Your history has become facts of manageable size.",
        "The archive closes at never and needs no library card.",
    )

    private val insightMessages = listOf(
        "The numbers formed a committee and found a trend.",
        "This chart is not a rectangular prophecy.",
        "Your average has arrived looking statistically respectable.",
        "A downward line is gravity earning its keep.",
        "The data refuses to become mystical.",
        "Statistics volunteered to hold the clipboard.",
        "Your smoking events now travel in labelled herds.",
        "The graph has opinions but no enforcement powers.",
        "Arithmetic converted smoke into something visible.",
        "Patterns emerge when chaos completes the forms.",
        "The daily total looks surprised to be here.",
        "Your trend chose the scenic route.",
        "The bars are informative and entirely non-alcoholic.",
        "Numbers stand straight because curves require permits.",
        "The dashboard found order under several Tuesdays.",
        "One smaller total remains statistically charming.",
        "The data misplaced its crystal ball.",
        "Your longest interval applied for an extension.",
        "The chart measures cigarettes, not personal worth.",
        "Averages smooth bumps and occasionally furniture.",
        "The selected dates agreed to be compared peacefully.",
        "Progress zigzags because straight lines are showing off.",
        "The numbers are sober even when Saturday was not.",
        "This graph contains fewer dragons than expected.",
        "The total required no summoned accountant.",
        "Statistics conceal their dreadful handwriting.",
        "A quiet trend still has excellent indoor manners.",
        "The dashboard translates memory into polite bars.",
        "Your data dressed formally for the occasion.",
        "The chart refuses to panic about larger axes.",
        "Every interval proves time happened between cigarettes.",
        "The average is neither monarch nor therapist.",
        "A custom range excludes nosy months.",
        "The graph removed the smoke and kept the plot.",
        "Your numbers wear comfortable geometry.",
        "The highest day has been denied a parade.",
        "A lower bar deserves a quiet nod.",
        "The data is local, unlike galactic gossip.",
        "Trends take time because causality is understaffed.",
        "This dashboard distinguishes half from mostly half.",
        "The figures irritate vague recollections.",
        "Progress exists even when it forgets to pose.",
        "The chart is yesterday wearing graph paper.",
        "Numbers cannot quit for you, citing union rules.",
        "The selected metric has put on its official hat.",
        "Averages are useful servants and dreadful captains.",
        "The data noticed things without judging them.",
        "Your best interval is polishing its medal.",
        "The graph offers perspective without additional smoke.",
        "Statistics are mirrors, not fortune tellers.",
        "The trend bends because reality dislikes rulers.",
        "Your smoking events surrendered their aliases.",
        "The dashboard emotes only on weekends.",
        "One day is a very small parliament of data.",
        "The numbers suggest direction without a band.",
        "Your chart has no secret agenda.",
        "The totals await curiosity's arrival.",
        "Progress hides where drama forgot to look.",
        "The mathematics is mostly harmless before midnight.",
        "This graph is smoke after university.",
    )

    private val settingsMessages = listOf(
        "Preferences are free will with toggle switches.",
        "Adjust the universe gently; the screws are decorative.",
        "Your daily target is not a parking fine.",
        "The export button is a lifeboat for commas.",
        "Your data cancelled its travel plans.",
        "Settings are where chaos chooses a theme.",
        "A kind target beats a tyrant with a spreadsheet.",
        "The configuration department has gone to lunch.",
        "Your preferences require no galactic permission.",
        "A backup is memory wearing a parachute.",
        "The database is local and socially reserved.",
        "Import carefully; the old universe will be replaced.",
        "Export before pressing buttons labelled destiny.",
        "This page controls everything that consented.",
        "Your target will not disappoint the constellations.",
        "The app requests no passport or home planet.",
        "A CSV is a spreadsheet that packed lightly.",
        "The settings remain calm when toggled.",
        "Your data has no cloud and excellent visibility.",
        "Choose a target Tuesday will recognize.",
        "The import button takes replacement literally.",
        "Your preferences live among discreet electrons.",
        "No setting can alter gravity yet.",
        "The daily limit carries no tiny handcuffs.",
        "Backups stop facts becoming adventurous folklore.",
        "Defaults exist because decisions require snacks.",
        "This menu is safer than its confidence suggests.",
        "Your settings became machine optimism.",
        "A sensible export confuses tomorrow's catastrophe.",
        "The database loves transactions and dislikes surprises.",
        "No committee hears when your target changes.",
        "The imaginary app lock requires sensible phone guarding.",
        "Your CSV contains commas trained for indoor use.",
        "Settings persist because forgetting seemed impolite.",
        "The target box rejects motivational yelling.",
        "Import validates reality before replacing it.",
        "Your information remains private and pleased.",
        "A toggle is a lever with enormous self-esteem.",
        "The export file deserves considerate handling.",
        "Daily goals improve without villainous laughter.",
        "This screen contains trace amounts of destiny.",
        "Your device guards these smoky chronicles alone.",
        "The settings page has no moral opinions.",
        "Changed preferences cause approved improbability only.",
        "Your backup may travel farther than the database.",
        "Controls are labelled because telepathy missed its deadline.",
        "Import leaves your target quietly seated.",
        "The app enjoys having no internet permission.",
        "Your number need not impress an interstellar auditor.",
        "Configuration is indecision with better furniture.",
        "The save button believes in second chances.",
        "Your export is portable but unlikely to escape.",
        "No preference is permanent except changing it.",
        "A target can be ambitious without becoming theatrical.",
        "This menu was tested on hypothetical planets.",
        "A local database avoids gossip at light speed.",
        "The settings await instructions and a biscuit.",
        "Your choices require no ceremonial smoke.",
        "The configuration remains mostly harmless.",
        "Save calmly; the universe has backed away.",
    )

    private val smokedMessages = listOf(
        "The cigarette has been logged and stripped of its alibi.",
        "Accuracy has entered wearing sensible shoes.",
        "The event is official, though nobody ordered a plaque.",
        "A tiny clerk has stamped this surprisingly honest.",
        "The cigarette now belongs to arithmetic.",
        "The log accepts evidence without raising an eyebrow.",
        "One smoky incident has acquired a timestamp.",
        "The database knows but remains discreet.",
        "Honesty defeated creative accounting again.",
        "The event was filed under Actually Happened.",
        "A fact landed safely in local storage.",
        "The cigarette can no longer use an alias.",
        "Your chart will process this professionally.",
        "The paperwork is needlessly immaculate.",
        "One combustion episode joined the census.",
        "The log nodded and returned to its tea.",
        "This cigarette is data with poor ventilation.",
        "The record remains emotionally underqualified.",
        "A timestamp pinned the event to reality.",
        "Statistics has received the parcel.",
        "The cigarette is counted, not applauded.",
        "Your honesty inconvenienced several optimistic guesses.",
        "The entry arrived without a moral soundtrack.",
        "The universe continues with better documentation.",
        "A fact replaced one smoky memory.",
        "The log filed this beneath Useful Truths.",
        "Tomorrow's graph has better intelligence now.",
        "The cigarette became a diminished decimal.",
        "The database swallowed the fact whole.",
        "Your record remains honest despite reality.",
        "The event is logged; panic is optional.",
        "A small truth entered a dark theme.",
        "The cigarette now works for the trend line.",
        "The facts gained one flammable colleague.",
        "This entry brought smoke but no excuses.",
        "The log records events, not verdicts.",
        "A tiny statistic started its office job.",
        "The cigarette surrendered to basic numeracy.",
        "The event is safe among awkward facts.",
        "Your tap prevented historical vagueness.",
        "The record expanded by one honest nuisance.",
        "This cigarette is past tense with metadata.",
        "The database remains neutral and rectangular.",
        "The event checked in under its real name.",
        "Another fact escaped the fog of memory.",
        "The log accepted delivery without judgement.",
        "Your future average has been informed.",
        "The cigarette became administrative truth.",
        "The entry is complete; trumpets were cancelled.",
        "A clerk has reached for a clipboard.",
        "The incident is documented and unmysterious.",
        "The timeline made room without complaining.",
        "The truth fits between two timestamps.",
        "Your data is richer by one poor investment.",
        "The event possesses all required paperwork.",
        "The cigarette joined a graph unwillingly.",
        "The record salutes your accuracy briefly.",
        "This fact escaped nicotine's editorial control.",
        "The log remains calm and fireproof enough.",
        "Recorded without judgement or unreliable narrators.",
    )

    private val resistedMessages = listOf(
        "The craving has been denied docking clearance.",
        "Your lungs sent an unsigned thank-you note.",
        "Nicotine called a meeting and nobody attended.",
        "The urge left to reconsider its career.",
        "Free will made an unscheduled appearance.",
        "The cigarette that never happened looks excellent.",
        "You outwaited chemistry and its dramatic hat.",
        "The craving brought thunder but forgot the storm.",
        "One urge has been returned to sender.",
        "Your habit has discovered the word no.",
        "The nicotine gremlin lost another election.",
        "A craving passed without planning permission.",
        "Your lungs are updating their holiday brochure.",
        "The urge demanded tribute and received silence.",
        "You turned nicotine into an ordinary pause.",
        "The craving has been placed on hold.",
        "One chemical tantrum ended without witnesses.",
        "Your lighter missed another professional opportunity.",
        "The urge departed by the tradesman's exit.",
        "You declined smoke and retained the break.",
        "Nicotine filed a complaint in invisible ink.",
        "The craving failed its entrance examination.",
        "Your lungs awarded you a microscopic medal.",
        "The habit blinked first and denies it.",
        "One cigarette remained successfully hypothetical.",
        "The urge was urgent only in its autobiography.",
        "You survived a molecule's sternest memo.",
        "The craving went elsewhere to exaggerate.",
        "Your smoke-free interval gained another room.",
        "Nicotine's emergency committee adjourned in confusion.",
        "The urge was defeated by ordinary time.",
        "Your lungs approve without becoming sentimental.",
        "A cigarette was cancelled for insufficient plot.",
        "The craving left no forwarding address.",
        "You waited while the urge forgot its lines.",
        "One impulse discovered it is not management.",
        "The habit was overruled by its host.",
        "Your next breath arrived without special effects.",
        "The craving's paperwork was magnificently incomplete.",
        "You postponed combustion beyond its attention span.",
        "Nicotine has been asked to wait outside.",
        "The urge lost interest before you lost patience.",
        "Your lungs quietly cancelled the fog machine.",
        "A craving vanished into routine maintenance.",
        "You said no without a planetary council.",
        "The cigarette remained theoretical and poorly funded.",
        "One urge was archived under Nice Try.",
        "Your habit encountered an unexpected plot hole.",
        "Not much happening defeated the craving.",
        "Nicotine's proposal died peacefully in committee.",
        "You made inaction look improbably productive.",
        "The urge passed while causality made tea.",
        "Your lungs requested an encore of nothing.",
        "A cigarette failed to materialize on schedule.",
        "The craving was shown the airlock politely.",
        "You outlasted an urge with no calendar.",
        "The habit retreated to its paperwork bunker.",
        "One smoky possibility became harmless fiction.",
        "The universe recorded a point in your favour.",
        "You resisted, and the cosmos remained understated.",
    )

    private val messages = mapOf(
        HumorTopic.TODAY to todayMessages,
        HumorTopic.HISTORY to historyMessages,
        HumorTopic.INSIGHTS to insightMessages,
        HumorTopic.SETTINGS to settingsMessages,
    )

    fun next(topic: HumorTopic, previous: String? = null, random: Random = Random.Default): String {
        val choices = messages.getValue(topic)
        val eligible = choices.filterNot { it == previous }.ifEmpty { choices }
        return eligible[random.nextInt(eligible.size)]
    }

    fun smoked(amount: Double, random: Random = Random.Default): String =
        "${if (amount == 1.0) "Whole cigarette" else "Half cigarette"} logged. ${smokedMessages.random(random)}"

    fun resisted(random: Random = Random.Default): String = resistedMessages.random(random)

    fun allFor(topic: HumorTopic): List<String> = messages.getValue(topic)

    fun allSmokedFollowUps(): List<String> = smokedMessages

    fun allResistedCompliments(): List<String> = resistedMessages
}
